services:
  redis:
    image: redis
    restart: always
    networks:
      - backend
    volumes:
      - ./saved/redis:/data

  battle-royale-server:
    image: node:24-alpine
    volumes:
      - ./battle-royale-server/:/app
    restart: always
    command: sh -c "npm i && npm run build && npm run start"
    working_dir: /app
    networks:
      - backend
    ports:
      - "8000:8000"
    env_file:
      - ./battle-royale-server/.env

networks:
  backend:
